### ISSUE TITLE
Is the trained vilbert-multi-task model available so that other researchers can query it? 

### ISSUE THREAD

**Issue by benotti** [Cloud-CV/vilbert-multi-task#4]
That is, I am wodering whether it is available outside this demo. I do not have the computing power to train it from scratch. Thanks!

**Comment by RishabhJain2018** [comment]
Hi @benotti ,
I think it is available here: https://github.com/facebookresearch/vilbert-multi-task/blob/master/demo.ipynb

Please close this issue if it resolves your query.

**Comment by RishabhJain2018** [comment]
Closing it due to inactivity!
